apiVersion: apps/v1
kind: Deployment
metadata:
    name: ea-demo-project
spec:
  replicas: 1
  revisionHistoryLimit: 5 #imiting the number of old replicasets that Kubernetes keeps for rollback purposes
  selector:
    matchLabels:
      app: ea-demo-project
  strategy: # DEPLOYMENT STRATEGY
    rollingUpdate:
      maxSurge: 1 # as an absolute number of replicas
      maxUnavailable: 25% # as % of the replicas
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ea-demo-project
    spec:
      containers:
        - name: ea-demo-project
          image: ngaurav07/k8s-spring-demo:v1.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health/liveness
          #     port: 8080
          #   initialDelaySeconds: 60
          #   periodSeconds: 15
          #   timeoutSeconds: 10
          # readinessProbe:
          #     httpGet:
          #       path: /actuator/health/readiness
          #       port: 8080
          #     initialDelaySeconds: 60
          #     periodSeconds: 10
          #     timeoutSeconds: 10
